### ISSUE TITLE
flutter_localization conflict with kalender 0.3.7

### ISSUE THREAD

**Issue by GSFdev24** [channdara/flutter_localization#17] opened 2024-04-23 09:49 UTC
Hello,

 i want to use in my project the library component  **kalender**  but the latest version of this library use the intl 0.19 that 
goes into conflict with the flutter_localization that use intl 0.18.1.

Is there a possibility that flutter_localization will be updated, so that it can also use the new version of the intl library? 

Thank you,Regards

**Comment by channdara** [comment] 2024-04-24 01:57
@GSFdev24 
I'm sad to say that I cannot update the **intl**. Since this package (flutter_localization) is not dependent on **intl** directly but depends on **Flutter SDK flutter_localizations** (the one that uses the intl 0.18.1). We have to wait for the Flutter update for this.

There is a workaround, you need to switch the Flutter channel to **master** (which is not recommended) and the issue is solved.

**Comment by GSFdev24** [comment] 2024-04-24 08:20
> @GSFdev24 I'm sad to say that I cannot update the **intl**. Since this package (flutter_localization) is not dependent on **intl** directly but depends on **Flutter SDK flutter_localizations** (the one that uses the intl 0.18.1). We have to wait for the Flutter update for this.
> 
> There is a workaround, you need to switch the Flutter channel to **master** (which is not recommended) and the issue is solved. But you might get other issues caused by the **master** channel.

Ok, i understand thank you

**Comment by channdara** [comment] 2024-05-18 03:55
Look like **Flutter SDK flutter_localizations** has been updated their **intl** version in the latest Flutter version. I will close this case for now. Thank you.

**Closed** 2024-05-18 03:55 UTC
